version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  producer:
    image: rabbitmq-poc/producer
    build: ./producer
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    restart: always

  consumer1:
    image: rabbitmq-poc/consumer1
    build: ./consumer1
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
    restart: always

  consumer2:
    image: rabbitmq-poc/consumer2
    build: ./consumer2
    ports:
      - 3002:3002
    depends_on:
      - rabbitmq
    restart: always
