version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    volumes:
      - './data:/var/lib/rabbitmq/mnesia'
    ports:
      - 5672:5672
      - 15672:15672

  producer:
    build:
      context: ./producer
      dockerfile: ../Dockerfile
    volumes:
      - './producer/:/usr/src/app'
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    restart: always

  consumer1:
    build:
      context: ./consumer1
      dockerfile: ../Dockerfile
    volumes:
      - './consumer1/:/usr/src/app'
    environment: 
      - PORT=3001
      - EXCHANGE=kwetter
      - QNAME=consumer1
      - MONGO_URL=mongodb://root:root@0.0.0.0:27017/consumer1?authSource=admin
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
    restart: always

  consumer2:
    build:
      context: ./consumer2
      dockerfile: ../Dockerfile
    volumes:
      - './consumer2/:/usr/src/app'
    environment: 
      - PORT=3002
      - EXCHANGE=kwetter
      - QNAME=consumer2
      - MONGO_URL=mongodb://root:root@0.0.0.0:27017/consumer2?authSource=admin
    ports:
      - 3002:3002
    depends_on:
      - rabbitmq
    restart: always
